name: PHPStan CI

on: push

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - name: Startup
        uses: actions/checkout@v2
        with:
          path: src
      - name: Checkout NGEssentials
        uses: actions/checkout@v2
        with:
          repository: NetherGamesMC/NGEssentials
          token: ${{ secrets.ng_token }}
          submodules: true
          path: NGEssentials
      - name: Run PHPStan
        uses: nxtlvlsoftware/pmmp-phpstan-action@3
        with:
          phpstan-config: src/phpstan.neon.dist